// The Choroboros editor window rebuilt for the film, for the five engines and the white Create
// canvas: the top bar (film/lib/topbar.js) over the body plate drawn from the plugin's own
// bitmaps. Geometry, readouts and chrome follow the release-candidate editor (f984c9a); see
// film/UI_FIDELITY.md for the sources and every measured difference.
//
//   const p = createPlate("green", { parent, scale: 0.8, x: 96, y: 318 });
//   p.requireRender(cues, "R02", 16, 20);          // in build(): prepare the frames it will show
//   p.setState(cues.plateStateAt("R02", t));      // in render(t)
//   p.place({ x, y, scale, dx });                 // camera / drift, any time
//   p.focus({ on: "rate", zoom: 2, at: [540, 900] }); // close-up: a control (or body point) at a
//                                                  // screen point; hi-res art above scale 1
//
// Plate px = editor px x K (K = 1400 / 638, one scale for x and y, as the editor draws). The body
// is 1400 x 724.14 (the 638 x 330 editor body; the backpanel bitmap is stretched into it exactly
// as the editor stretches it), origin at the body's top-left. With the top bar (default) the
// window is 1400 x 847.02 (638 x 386 editor px) and the body sits 122.88 px lower; place() and
// width/height refer to the whole window, toScreen()/controlScreenRect() take body coordinates.
// Values are display units (rate Hz, offset degrees, the rest percent) and map to filmstrip
// frames, thumb x and readout text exactly as the plugin does. Filmstrip frames are per-frame
// images (film/tools/prep_gui.py) shown by visibility; the plate is plain DOM and inline SVG,
// never a canvas, so it may be scaled by a CSS transform deterministically (every bitmap is
// resampled once, from its source pixels to the screen; text and the top bar stay vector).

import { PLATE_W, READOUT_COLOR, artFor } from "./layout.js";
import { pFromValue, knobFrameMain, knobFrameMix, formatReadout, SWITCH_OFF, SWITCH_ON } from "./cues.js";
import { el, setStyle, px, clamp, rgba, TAU } from "./util.js";
import { TopBar, HEADER_EDITOR_H, PLATE_FONTS, advance, roundToInt, toNearestInt } from "./topbar.js";

const KNOBS = ["rate", "depth", "offset", "width"];
const READOUTS = ["rate", "depth", "offset", "width", "color", "mix"];

// Editor px -> plate px. The editor lays out and paints everything at one scale and stretches the
// 1400 x 725 backpanel bitmap into its 638 x 330 body (PluginEditor::paint, drawImage into the
// canvas bounds), so the plate uses one factor K for x and y and stretches the bitmap the same way.
const EDITOR_W = 638;
const BODY_H = 330;
export const K = PLATE_W / EDITOR_W;
export const KX = K;
export const KY = K;
/** Body height in plate px (330 editor px = 724.14). */
export const BODY_PX_H = BODY_H * K;
/** Height of the top bar in plate px (56 editor px). */
export const HEADER_PX = HEADER_EDITOR_H * K;
/**
 * Plate scale above which a knob frame (300 px source for a 127 editor px knob, 278.7 plate px)
 * is magnified: 300 / 278.7. The backpanel's hi-res art (see layout.js) takes over above 1.0.
 */
export const KNOB_NATIVE_SCALE = 300 / (127 * K);
const bx = (x) => x * KX;
const by = (y) => (y - HEADER_EDITOR_H) * KY; // editor y (window) -> body plate y

// GENERATED by `python3 film/tools/rc_layout.py --js` (release-candidate f984c9a factory defaults).
// Editor px at 1x (window 638 x 386, body y 56..386). Do not edit by hand.
const RC = {
  green: {"rate":[34,128,127,127],"depth":[167,128,127,127],"offset":[364,128,127,127],"width":[493,128,127,127],"color":[182,276,295,62],"mix":[535,309,53,53],"values":{"rate":[53,249,87,30],"depth":[186,248,87,30],"offset":[385,249,87,30],"width":[514,249,87,30],"color":[300,328,59,23],"mix":[536,357,50,14]},"hq":[271,142,115,115],"fontH":{"main":13.6714,"color":13.6714,"mix":10.5},"fx":{"rate":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"depth":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"offset":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"width":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"color":{"glowAlpha":0.39,"glowSpread":3.48,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,-1.6,0.0,0],"bottom":[0.11,0.0,-1.27,0.0,0],"blur":1.34,"squash":0.82},"mix":{"glowAlpha":0.26,"glowSpread":0.07,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,1.7,0.0,0],"bottom":[0.1,0.0,-1.16,0.0,0],"blur":0.7,"squash":0.95}}},
  blue: {"rate":[41,137,112,112],"depth":[172,137,112,112],"offset":[371,137,112,112],"width":[503,137,112,112],"color":[182,276,295,62],"mix":[535,309,51,51],"values":{"rate":[52,247,87,30],"depth":[183,247,87,30],"offset":[384,248,87,30],"width":[516,247,87,30],"color":[300,326,59,23],"mix":[535,355,50,14]},"hq":[271,142,115,115],"fontH":{"main":13.6714,"color":13.6714,"mix":10.5},"fx":{"rate":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"depth":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"offset":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"width":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"color":{"glowAlpha":0.39,"glowSpread":3.48,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,-1.6,0.0,0],"bottom":[0.11,0.0,-1.27,0.0,0],"blur":1.34,"squash":0.82},"mix":{"glowAlpha":0.26,"glowSpread":0.07,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,1.7,0.0,0],"bottom":[0.1,0.0,-1.16,0.0,0],"blur":0.7,"squash":0.95}}},
  red: {"rate":[39,136,115,115],"depth":[170,136,115,115],"offset":[369,136,115,115],"width":[501,136,115,115],"color":[182,275,295,66],"mix":[535,309,51,51],"values":{"rate":[52,247,87,30],"depth":[183,247,87,30],"offset":[384,248,87,30],"width":[516,247,87,30],"color":[300,326,59,23],"mix":[535,355,50,14]},"hq":[271,142,115,115],"fontH":{"main":13.6714,"color":13.6714,"mix":10.5},"fx":{"rate":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"depth":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-4.02,0.0,4],"bottom":[0.15,0.11,-0.33,0.0,1],"blur":5.0,"squash":0.84},"offset":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":-0.56,"top":[0.15,-1.46,-2.95,0.0,4],"bottom":[0.15,0.11,-0.81,0.0,1],"blur":5.0,"squash":0.84},"width":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.33,0.0,4],"bottom":[0.15,0.11,0.06,0.0,1],"blur":5.0,"squash":0.84},"color":{"glowAlpha":0.39,"glowSpread":3.48,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,-1.6,0.0,0],"bottom":[0.11,0.0,-1.27,0.0,0],"blur":1.34,"squash":0.82},"mix":{"glowAlpha":0.26,"glowSpread":0.07,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,1.7,0.0,0],"bottom":[0.1,0.0,-1.16,0.0,0],"blur":0.7,"squash":0.95}}},
  purple: {"rate":[41,127,113,113],"depth":[173,127,113,113],"offset":[371,127,113,113],"width":[502,127,113,113],"color":[182,269,295,68],"mix":[534,309,54,54],"values":{"rate":[53,249,87,30],"depth":[185,248,87,30],"offset":[385,249,87,30],"width":[516,249,87,30],"color":[300,327,59,23],"mix":[536,357,50,14]},"hq":[271,142,115,115],"fontH":{"main":13.6714,"color":13.6714,"mix":10.5},"fx":{"rate":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"depth":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"offset":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":-0.56,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,-0.81,0.0,1],"blur":5.0,"squash":0.84},"width":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.24,-1.46,-3.33,0.0,4],"bottom":[0.25,0.11,0.06,0.0,1],"blur":5.0,"squash":0.84},"color":{"glowAlpha":0.39,"glowSpread":3.48,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,-1.6,0.0,0],"bottom":[0.11,0.0,-1.27,0.0,0],"blur":1.34,"squash":0.82},"mix":{"glowAlpha":0.26,"glowSpread":0.07,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,1.7,0.0,0],"bottom":[0.1,0.0,-1.16,0.0,0],"blur":0.7,"squash":0.95}}},
  black: {"rate":[39,131,115,115],"depth":[170,131,115,115],"offset":[369,131,115,115],"width":[501,131,115,115],"color":[182,277,295,61],"mix":[535,309,51,51],"values":{"rate":[52,248,87,30],"depth":[183,248,87,30],"offset":[384,249,87,30],"width":[516,248,87,30],"color":[300,327,59,23],"mix":[535,355,50,14]},"hq":[271,142,115,115],"fontH":{"main":13.6714,"color":13.6714,"mix":10.5},"fx":{"rate":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"depth":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"offset":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"width":{"glowAlpha":0.4,"glowSpread":3.5,"charDX":-0.65,"charDY":0.0,"top":[0.15,-1.46,-3.16,0.0,4],"bottom":[0.15,0.11,0.68,0.0,1],"blur":5.0,"squash":0.84},"color":{"glowAlpha":0.39,"glowSpread":3.48,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,-1.6,0.0,0],"bottom":[0.11,0.0,-1.27,0.0,0],"blur":1.34,"squash":0.82},"mix":{"glowAlpha":0.26,"glowSpread":0.07,"charDX":0.0,"charDY":0.0,"top":[0.09,0.0,1.7,0.0,0],"bottom":[0.1,0.0,-1.16,0.0,0],"blur":0.7,"squash":0.95}}},
};
const RC_FLIP = {"main":{"ms":60,"travel":0.25,"travelOut":0.5,"travelIn":0.5,"shear":0.3,"minScale":0.8},"color":{"ms":60,"travel":0.25,"travelOut":0.5,"travelIn":0.5,"shear":0.3,"minScale":0.8},"mix":{"ms":60,"travel":0.25,"travelOut":0.5,"travelIn":0.5,"shear":0.3,"minScale":0.8}};

// The clean white Create draft ("New Engine", CreateDocumentFactory): white main and mix sheets,
// the shared lever sheet, the default (green) COLOR thumb and value text in #303030. It is drawn on
// the Green factory geometry (not verified against a render: Create needs a licence).
RC.white = RC.green;
const ENGINE_NAMES = { green: "Green", blue: "Blue", red: "Red", purple: "Purple", black: "Black" };

/** Editor-px geometry of an engine (knobs, color slider, mix, hq, values). */
export function plateGeometry(engine) {
  const g = RC[engine];
  if (!g) throw new Error(`plate: unknown engine ${engine}`);
  return g;
}

// Readout text ---------------------------------------------------------------------------------

const isDigit = (c) => c >= "0" && c <= "9";
const jround = roundToInt; // juce::roundToInt (half to even)
const intRect = (x, y, w, h) => toNearestInt([x, y, w, h]); // Rectangle<float>::toNearestInt

// Every readout, so the stage can lay them out again once the fonts have loaded.
const allReadouts = new Set();
export function relayoutReadouts() {
  for (const r of allReadouts) {
    r.key = null;
    if (r.last != null) r.set(r.last);
  }
}

/**
 * One value readout, drawn like LabelWithContainer::paint for a value label in the RC editor:
 * JetBrains Mono SemiBold at the label's JUCE height, every character centred in its own slot
 * (digits share one slot width), the run centred in the inner box (factory panels use
 * Justification::centred), each slot snapped to whole editor px (toNearestInt). Per glyph: eight
 * glow copies, a top and a bottom reflection (squashed, rotated, with four blur copies each), then
 * the glyph. A digit that changes flips over 60 ms: fade, squash to 80 %, shear 0.30.
 */
class Readout {
  constructor(parent, rect, fontH, color, fx, flip) {
    const [x, y, w, h] = rect;
    this.rect = rect;
    this.fontH = fontH;
    this.fx = fx;
    this.flip = flip;
    this.color = color;
    this.inner = [x + 1, y + 1, w - 2, h - 2];
    const font = PLATE_FONTS.mono;
    this.fontCss = `${font.weight} ${+(fontH * font.emPerHeight * KX).toFixed(4)}px "${font.family}"`;
    this.node = el("div", { parent, cls: "cb-readout", style: { position: "absolute", left: "0px", top: "0px", width: "0px", height: "0px", whiteSpace: "pre" } });
    this.cells = [];
    this.last = null;
    this.key = null;
    allReadouts.add(this);
  }

  _adv(ch) {
    return advance(ch, PLATE_FONTS.mono, this.fontH);
  }

  // One text node positioned at an editor-px int rect, centred like Graphics::drawText.
  _textNode(parent) {
    return el("div", {
      parent,
      style: { position: "absolute", left: "0px", top: "0px", textAlign: "center", whiteSpace: "pre", font: this.fontCss, color: this.color },
    });
  }

  // A glyph group: glow (shadows only), top reflection, bottom reflection, glyph.
  _group(parent) {
    const g = { glow: this._textNode(parent), top: this._textNode(parent), bottom: this._textNode(parent), main: this._textNode(parent) };
    g.glow.style.color = "transparent";
    return g;
  }

  _cell(i) {
    while (this.cells.length <= i) {
      const box = el("div", { parent: this.node, style: { position: "absolute", left: "0px", top: "0px", width: "0px", height: "0px", overflow: "visible" } });
      this.cells.push({ box, a: this._group(box), b: this._group(box) });
    }
    return this.cells[i];
  }

  /** Draw one glyph group for character ch in the float area (editor px) at alpha. */
  _drawGroup(g, ch, area, alpha, flipT, boxOrigin) {
    const fx = this.fx;
    const [ax, ay, aw, ah] = area;
    const show = alpha > 0.001;
    for (const n of [g.glow, g.top, g.bottom, g.main]) {
      if (n.__ch !== ch) {
        n.__ch = ch;
        n.textContent = ch;
      }
      setStyle(n, "display", show ? "block" : "none");
    }
    if (!show) return;
    const place = (n, r) => {
      setStyle(n, "left", px(bx(r[0]) - boxOrigin[0]));
      setStyle(n, "top", px(by(r[1]) - boxOrigin[1]));
      setStyle(n, "width", px(r[2] * KX));
      setStyle(n, "height", px(r[3] * KY));
      setStyle(n, "lineHeight", px(r[3] * KY));
    };
    const main = intRect(ax, ay, aw, ah);
    // Glow: eight copies at glowSpread, each rect snapped on its own.
    const s = fx.glowSpread;
    let glow = "";
    if (fx.glowAlpha > 0 && s > 0) {
      const dirs = [[-1, 0], [1, 0], [0, -1], [0, 1], [-0.7, -0.7], [0.7, -0.7], [-0.7, 0.7], [0.7, 0.7]];
      const c = rgba(this.color, alpha * fx.glowAlpha * 0.14);
      glow = dirs
        .map(([dx, dy]) => `${px((jround(ax + dx * s) - main[0]) * KX)} ${px((jround(ay + dy * s) - main[1]) * KY)} 0 ${c}`)
        .join(", ");
    }
    place(g.glow, main);
    setStyle(g.glow, "textShadow", glow);
    // Reflections: squash about the area's bottom (top copy) or top (bottom copy), rotate, blur.
    const refl = (n, spec, pivotBottom) => {
      const [ra, ox, oy, shear, rot] = spec;
      if (!(ra > 0)) {
        setStyle(n, "display", "none");
        return;
      }
      const r = [ax + ox + fx.charDX, ay + oy + fx.charDY, aw, ah];
      const ir = intRect(...r);
      place(n, ir);
      const sy = clamp(1 - fx.squash, 0.08, 1);
      const pivot = [r[0] + r[2] / 2, pivotBottom ? r[1] + r[3] : r[1]];
      setStyle(n, "transformOrigin", `${px((pivot[0] - ir[0]) * KX)} ${px((pivot[1] - ir[1]) * KY)}`);
      // JUCE applies the transform added last first: rotate, then squash, then shear (0 here).
      const sh = shear ? ` skewY(${+Math.atan(shear).toFixed(6)}rad)` : "";
      setStyle(n, "transform", `${sh} scale(1, ${+sy.toFixed(5)}) rotate(${rot}deg)`.trim());
      setStyle(n, "color", rgba(this.color, alpha * ra));
      const b = fx.blur;
      const bc = rgba(this.color, alpha * ra * 0.28);
      const blur = b > 0
        ? [[-1, 0], [1, 0], [0, -1], [0, 1]].map(([dx, dy]) => `${px((jround(r[0] + dx * b) - ir[0]) * KX)} ${px((jround(r[1] + dy * b) - ir[1]) * KY)} 0 ${bc}`).join(", ")
        : "";
      setStyle(n, "textShadow", blur);
    };
    refl(g.top, fx.top, true);
    refl(g.bottom, fx.bottom, false);
    // The glyph, with the flip's squash about its pivot and the shear about the label origin.
    place(g.main, main);
    setStyle(g.main, "opacity", alpha >= 1 ? "" : String(+alpha.toFixed(4)));
    if (flipT) {
      const { scale, pivotBottom, shearSign } = flipT;
      const k = (1 - scale) * this.flip.shear * shearSign;
      const py = pivotBottom ? ay + ah : ay; // label-local pivot is taken in window coords here
      const lx = this.rect[0];
      const ly = this.rect[1];
      // (x, y) -> (x, py + s (y - py) + k (x - lx)) with x, y relative to the label origin.
      setStyle(g.main, "transformOrigin", `${px(bx(lx) - bx(main[0]))} ${px(by(ly) - by(main[1]))}`);
      const f = (py - ly) * (1 - scale) * KY;
      setStyle(g.main, "transform", `matrix(1, ${+(k * (KY / KX)).toFixed(6)}, 0, ${+scale.toFixed(6)}, 0, ${+f.toFixed(4)})`);
    } else {
      setStyle(g.main, "transform", "");
      setStyle(g.main, "transformOrigin", "");
    }
  }

  /** value: "45%" or { text, from, progress } (see Cues.readoutAt). */
  set(value) {
    this.last = value;
    const v = typeof value === "string" ? { text: value, from: value, progress: 1 } : value;
    const flipping = v.from !== v.text && v.progress < 1;
    const p = flipping ? clamp(v.progress) : 1;
    const key = flipping ? `${v.from}>${v.text}@${p.toFixed(4)}` : v.text;
    if (key === this.key) return;
    this.key = key;

    const text = v.text;
    // Map the old digits onto the new text from the right (setAnimatedValueText).
    const mapped = text.split("");
    const flipIdx = new Set();
    let dir = 0;
    if (flipping) {
      const fromD = [];
      const toD = [];
      for (let i = 0; i < v.from.length; i++) if (isDigit(v.from[i])) fromD.push(i);
      for (let i = 0; i < text.length; i++) if (isDigit(text[i])) toD.push(i);
      let fi = fromD.length - 1;
      for (let ti = toD.length - 1; ti >= 0; ti--) {
        const at = toD[ti];
        const fd = fi >= 0 ? v.from[fromD[fi]] : " ";
        mapped[at] = fd;
        if (fd !== text[at]) flipIdx.add(at);
        fi--;
      }
      const num = (s) => {
        const t = s.replace(/[^0-9.-]/g, "");
        return t && t !== "-" && t !== "." ? parseFloat(t) : NaN;
      };
      const a = num(v.from);
      const b = num(text);
      if (Number.isFinite(a) && Number.isFinite(b)) dir = b > a ? 1 : b < a ? -1 : 0;
    }
    const old = mapped.join("");

    // Slot widths (LabelWithContainer::paint), editor px.
    const [ix, iy, iw, ih] = this.inner;
    let digitSlot = 0;
    for (let d = 0; d <= 9; d++) digitSlot = Math.max(digitSlot, this._adv(String(d)));
    digitSlot = Math.max(digitSlot, ih * 0.26);
    const symbolMin = Math.max(ih * 0.16, digitSlot * 0.38);
    const pad = Math.max(0.8, ih * 0.03);
    const slot = (ch) => {
      if (ch === " ") return symbolMin * 0.9;
      const m = this._adv(ch);
      if (isDigit(ch)) return Math.max(digitSlot, m * 1.05) + pad;
      return Math.max(symbolMin, m * 1.3) + pad;
    };
    const widths = [];
    let total = 0;
    for (let i = 0; i < text.length; i++) {
      const w = Math.max(slot(text[i]), slot(i < old.length ? old[i] : text[i]));
      widths.push(w);
      total += w;
    }
    let x = ix + iw / 2 - total / 2; // Justification::centred

    const F = this.flip;
    const minScale = F.minScale;
    for (let i = 0; i < text.length; i++) {
      const w = widths[i];
      const cell = this._cell(i);
      const area = [x, iy, w, ih];
      if (!flipIdx.has(i)) {
        setStyle(cell.box, "overflow", "visible");
        setStyle(cell.box, "left", "0px");
        setStyle(cell.box, "top", "0px");
        setStyle(cell.box, "width", "0px");
        setStyle(cell.box, "height", "0px");
        this._drawGroup(cell.a, text[i], area, 1, null, [0, 0]);
        this._drawGroup(cell.b, " ", area, 0, null, [0, 0]);
      } else {
        // reduceClipRegion(charArea.expanded(0, travel + 2).toNearestInt()) for this character.
        const travelOut = F.travel * F.travelOut;
        const travelIn = F.travel * F.travelIn;
        const clipPad = Math.max(travelOut, travelIn) + 2;
        const clip = intRect(x, iy - clipPad, w, ih + 2 * clipPad);
        const origin = [bx(clip[0]), by(clip[1])];
        setStyle(cell.box, "overflow", "hidden");
        setStyle(cell.box, "left", px(origin[0]));
        setStyle(cell.box, "top", px(origin[1]));
        setStyle(cell.box, "width", px(clip[2] * KX));
        setStyle(cell.box, "height", px(clip[3] * KY));
        const valueDown = dir < 0;
        const outDir = valueDown ? -1 : 1;
        const outArea = [x, iy + outDir * travelOut * p, w, ih];
        const inArea = [x, iy - outDir * travelIn * (1 - p), w, ih];
        this._drawGroup(cell.b, old[i], outArea, 1 - p, { scale: minScale + (1 - minScale) * (1 - p), pivotBottom: !valueDown, shearSign: valueDown ? -1 : 1 }, origin);
        this._drawGroup(cell.a, text[i], inArea, p, { scale: minScale + (1 - minScale) * p, pivotBottom: valueDown, shearSign: valueDown ? 1 : -1 }, origin);
      }
      setStyle(cell.box, "display", "block");
      x += w;
    }
    for (let k = text.length; k < this.cells.length; k++) setStyle(this.cells[k].box, "display", "none");
  }

  clear() {
    this.key = "";
    for (const c of this.cells) setStyle(c.box, "display", "none");
  }
}

// Frame stacks ---------------------------------------------------------------------------------

/**
 * One control drawn from per-frame images: an <img> per frame that the scenes declared, all
 * decoded before frame 0, shown by visibility. Nothing is loaded or decoded during the render, so
 * a seek to any time shows the right frame (never swap img.src per frame).
 */
class FrameStack {
  constructor(parent, urlOf, x, y, w, h, label) {
    this.urlOf = urlOf;
    this.label = label;
    this.node = el("div", { parent, style: { position: "absolute", left: px(x), top: px(y), width: px(w), height: px(h) } });
    this.imgs = new Map();
    this.cur = null;
  }

  require(frames) {
    for (const f of frames) {
      if (this.imgs.has(f)) continue;
      const img = el("img", { parent: this.node, attrs: { src: this.urlOf(f), alt: "", draggable: "false" } });
      Object.assign(img.style, { position: "absolute", left: "0px", top: "0px", width: "100%", height: "100%", visibility: "hidden" });
      this.imgs.set(f, img);
    }
  }

  has(f) {
    return this.imgs.has(f);
  }

  show(f) {
    if (f === this.cur) return;
    if (f != null && !this.imgs.has(f)) {
      throw new Error(`plate: ${this.label} frame ${f} was not prepared; call plate.require()/requireRender() in build()`);
    }
    if (this.cur != null) this.imgs.get(this.cur).style.visibility = "hidden";
    this.cur = f;
    if (f != null) this.imgs.get(f).style.visibility = "";
  }

  setOpacity(a) {
    setStyle(this.node, "opacity", a >= 1 ? "" : String(+a.toFixed(4)));
    setStyle(this.node, "visibility", a > 0 ? "" : "hidden");
  }

  urls() {
    return [...this.imgs.keys()].map((f) => this.urlOf(f));
  }
}

// Window chrome drawn by the editor over the body -------------------------------------------------

const SVGNS = "http://www.w3.org/2000/svg";
function svgEl(tag, attrs, parent) {
  const n = document.createElementNS(SVGNS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, typeof v === "number" ? String(+v.toFixed(4)) : v);
  if (parent) parent.appendChild(n);
  return n;
}

/**
 * The resize corner: JUCE's ResizableCornerComponent (18 x 18 at 620, 368; LookAndFeel_V2 draws
 * four light/dark line pairs, 1.35 px) and the three grip strokes paintOverChildren adds
 * (#d7d2c6 @ 0.34, 0.75 px). Drawn in editor px inside the body.
 */
function drawCorner(parent) {
  const svg = svgEl("svg", { width: bx(EDITOR_W), height: BODY_PX_H, viewBox: `0 ${HEADER_EDITOR_H} ${EDITOR_W} ${BODY_H}` });
  Object.assign(svg.style, { position: "absolute", left: "0px", top: "0px", overflow: "hidden", pointerEvents: "none" });
  parent.appendChild(svg);
  const [cx, cy, cw, ch] = [620, 368, 18, 18];
  const clip = svgEl("clipPath", { id: `cb-corner-${(drawCorner.n = (drawCorner.n || 0) + 1)}` }, svg);
  svgEl("rect", { x: cx, y: cy, width: cw, height: ch }, clip);
  const g = svgEl("g", { "clip-path": `url(#${clip.id})` }, svg);
  const t = Math.min(cw, ch) * 0.075;
  for (let i = 0; i < 1; i += 0.3) {
    svgEl("line", { x1: cx + cw * i, y1: cy + ch + 1, x2: cx + cw + 1, y2: cy + ch * i, stroke: "#d3d3d3", "stroke-width": t }, g);
    svgEl("line", { x1: cx + cw * i + t, y1: cy + ch + 1, x2: cx + cw + 1, y2: cy + ch * i + t, stroke: "#a9a9a9", "stroke-width": t }, g);
  }
  const size = 7;
  const inset = 5;
  const r = [EDITOR_W - inset - size, 386 - inset - size];
  for (let i = 1; i < 3; i++) {
    const o = (i * size) / 3;
    svgEl("line", { x1: r[0] + size - o, y1: r[1] + size, x2: r[0] + size, y2: r[1] + size - o, stroke: "rgba(215,210,198,0.34)", "stroke-width": 0.75 }, svg);
  }
  return svg;
}

// Plate ---------------------------------------------------------------------------------------

const range = (a, b) => {
  const out = [];
  for (let f = Math.min(a, b); f <= Math.max(a, b); f++) out.push(f);
  return out;
};

// Lever travel inside the switch cell (512 px atlas frames): ball up to ball down, y 87..365
// around the pivot at cell y 226.
const LEVER = { cy: 226 / 512, size: 278 / 512 };

export class Plate {
  /**
   * engine: green | blue | red | purple | black | white (Create).
   * opts: { parent, scale, x, y (window top-left) or cx, cy (window centre), header (default true:
   * the top bar), hiRes (true: also load the prepared 2x backpanel and show it whenever the plate
   * is drawn above scale 1, the shipped 1400 px bitmap otherwise; "always": the 2x plate at any
   * scale; false: never; default: true when the plate is built above scale 1. Pass true for a plate
   * built small that focus() pushes in later: the 2x art is decoded before frame 0 like any image,
   * so it costs about 32 MB of decoded pixels per plate), litPlate ("editor" (default): the lit
   * plate at the 638 x 330 the editor's HQLitOverlay caches it at, magnified like the app, so the
   * HQ-on plate is as soft as in the app; "full": the 1400 px lit bitmap), thumb, readouts, state
   * (initial state; its frames are prepared) }.
   */
  constructor(engine, { parent = null, scale = 1, x = 0, y = 0, cx = null, cy = null, header = true, hiRes = null, litPlate = "editor", thumb = null, readouts = null, className = "", state = null } = {}) {
    if (!RC[engine]) throw new Error(`plate: unknown engine ${engine}`);
    this.engine = engine;
    this.G = RC[engine];
    this.white = engine === "white";
    this.art = artFor(engine);
    const hr = hiRes ?? scale > 1.0001;
    this.hiRes = !this.art.plate2x || !hr ? false : hr === "always" ? "always" : "auto";
    this.showThumb = thumb ?? true;
    this.showReadouts = readouts ?? true;
    this.headerH = header ? HEADER_PX : 0;
    this.width = PLATE_W;
    this.height = BODY_PX_H + this.headerH;

    this.el = el("div", { cls: `cb-plate cb-${engine} ${className}`.trim(), parent });
    Object.assign(this.el.style, { position: "absolute", left: "0px", top: "0px", transformOrigin: "0 0" });
    this.inner = el("div", { parent: this.el });
    Object.assign(this.inner.style, { position: "absolute", left: "0px", top: "0px", width: px(this.width), height: px(this.height), transformOrigin: "0 0", background: "#000000" });
    if (header) {
      this.topbar = new TopBar({
        parent: this.inner,
        k: KX,
        engineName: this.white ? "New Engine" : ENGINE_NAMES[engine],
        placeholder: this.white,
      });
    }
    this.body = el("div", { parent: this.inner, style: { position: "absolute", left: "0px", top: px(this.headerH), width: px(PLATE_W), height: px(BODY_PX_H), overflow: "hidden" } });

    // Backpanel: the shipped bitmap stretched into the body (plus the 2x art for close-ups), the lit
    // plate over it at the lever's lit amount (HQLitOverlay).
    const plateBg = (url, parent) =>
      el("div", {
        parent,
        style: {
          position: "absolute",
          left: "0px",
          top: "0px",
          width: px(PLATE_W),
          height: px(BODY_PX_H),
          backgroundImage: `url("${url}")`,
          backgroundSize: "100% 100%",
          backgroundRepeat: "no-repeat",
        },
      });
    const panel = (key) => {
      const wrap = el("div", { parent: this.body, style: { position: "absolute", left: "0px", top: "0px", width: px(PLATE_W), height: px(BODY_PX_H) } });
      const src = key === "plateOn" && litPlate === "editor" ? this.art.plateOnEditor : this.art[key];
      const lo = plateBg(src, wrap);
      const hi = this.hiRes ? plateBg(this.art.plate2x[key], wrap) : null;
      return { wrap, lo, hi };
    };
    this.plateOff = panel("plateOff");
    this.plateOn = panel("plateOn");
    Object.assign(this.plateOn.wrap.style, { opacity: "0", visibility: "hidden" });

    const rect = ([x0, y0, w, h]) => [bx(x0), by(y0), w * KX, h * KY];
    // Knobs: the _off and _on frames in an isolated group, the _on stack added with plus-lighter,
    // so the group is (1 - t) off + t on in premultiplied colour, which is what the editor's
    // drawCrossfadedFilmstripPair computes pixel by pixel while the HQ lever moves.
    this.knobs = {};
    for (const k of KNOBS) {
      const [kx, ky, w, h] = rect(this.G[k]);
      const group = el("div", { parent: this.body, style: { position: "absolute", left: px(kx), top: px(ky), width: px(w), height: px(h), isolation: "isolate" } });
      const mk = (on) => new FrameStack(group, (f) => this.art.knobFrame(k, on, f), 0, 0, w, h, `${engine} ${k}${on ? " on" : " off"}`);
      const off = mk(false);
      const on = this.white ? null : mk(true);
      if (on) setStyle(on.node, "mixBlendMode", "plus-lighter");
      this.knobs[k] = { off, on };
    }
    {
      const [mx, my, w, h] = rect(this.G.mix);
      this.mix = new FrameStack(this.body, (f) => this.art.mixFrame(f), mx, my, w, h, `${engine} mix`);
    }
    if (this.showThumb && this.art.thumb) {
      // LookAndFeel_V2::getSliderLayout indents a horizontal slider by getSliderThumbRadius
      // (min(12, h / 2)) at each end; drawLinearSlider / drawSliderThumb then draw the thumb at
      // the full height, image aspect (200 x 400), at most 20 % of that width, travelling between
      // 11.5 % insets. drawSliderThumb hands its float x, y, w, h to the int overload of
      // Graphics::drawImage, so the drawn rectangle is truncated to whole editor px (setState).
      const [sx0, sy, sw0, sh] = this.G.color;
      const indent = Math.min(12, Math.floor(sh * 0.5));
      const sx = sx0 + indent;
      const sw = sw0 - 2 * indent;
      const th = sh;
      const tw = Math.min(th * 0.5, sw * 0.2);
      this.thumbGeom = { x0: sx + sw * 0.115, x1: sx + sw - sw * 0.115, w: tw, h: th, y: sy + (sh - th) / 2 };
      this.thumb = el("div", {
        parent: this.body,
        style: {
          position: "absolute",
          top: px(by(Math.trunc(this.thumbGeom.y))),
          width: px(Math.trunc(tw) * KX),
          height: px(Math.trunc(th) * KY),
          backgroundImage: `url("${this.art.thumb}")`,
          backgroundSize: "100% 100%",
          backgroundRepeat: "no-repeat",
        },
      });
      // Until a state sets COLOR, the thumb rests at the factory default (50 %).
      this.thumb.style.left = px(bx(Math.trunc((this.thumbGeom.x0 + this.thumbGeom.x1) / 2 - tw / 2)));
    }
    {
      const [x0, y0, w, h] = rect(this.G.hq);
      // Two stacks, the lever frame under the fractional position and the next one, blended like
      // AnimatedToggleButton::paint ((1 - a) base + a next) in an isolated plus-lighter group.
      const group = el("div", { parent: this.body, style: { position: "absolute", left: px(x0), top: px(y0), width: px(w), height: px(h), isolation: "isolate" } });
      this.sw = [0, 1].map(() => new FrameStack(group, (f) => this.art.switchFrame(f), 0, 0, w, h, `${engine} switch`));
      setStyle(this.sw[1].node, "mixBlendMode", "plus-lighter");
    }
    this.readouts = {};
    if (this.showReadouts) {
      const color = READOUT_COLOR[engine];
      for (const r of READOUTS) {
        const fontH = r === "mix" ? this.G.fontH.mix : r === "color" ? this.G.fontH.color : this.G.fontH.main;
        const flip = r === "mix" ? RC_FLIP.mix : r === "color" ? RC_FLIP.color : RC_FLIP.main;
        this.readouts[r] = new Readout(this.body, this.G.values[r], fontH, color, this.G.fx[r], flip);
      }
    }
    drawCorner(this.body);
    // Everything in the body except the readouts: setGrade() filters these (colour = sound, v5).
    const readoutNodes = new Set(Object.values(this.readouts).map((r) => r.node));
    this._gradeNodes = [...this.body.children].filter((n) => !readoutNodes.has(n));
    this.cur = {};
    this.placement = { x: 0, y: 0, scale: 1, dx: 0, dy: 0 };
    this.place(cx != null ? { cx, cy, scale } : { x, y, scale });
    if (state) {
      this.require(state);
      this.setState(state);
    }
  }

  // Frames this state shows: { knobs: {rate: f,...}, mix: f, switch: [i0, i1], on, off }.
  // Main knobs (every engine and the white sheet): 10 x 10 frames read forward; factory mix: 13 x 12
  // read in reverse; the white mix (1632 px sheet): 10 x 10 read forward (drawRotarySlider).
  _framesOf(state) {
    const out = { knobs: {}, mix: null, sw: [], on: false, off: false };
    for (const k of KNOBS) {
      if (state.frames && state.frames[k] != null) out.knobs[k] = state.frames[k];
      else if (state[k] != null) out.knobs[k] = knobFrameMain(pFromValue(k, state[k]));
    }
    if (state.frames && state.frames.mix != null) out.mix = state.frames.mix;
    else if (state.mix != null) out.mix = this.white ? knobFrameMain(pFromValue("mix", state.mix)) : knobFrameMix(pFromValue("mix", state.mix));
    let sf = state.switchFrame;
    if (sf == null && state.hq != null) sf = state.hq ? SWITCH_ON : SWITCH_OFF;
    if (sf == null && this.white) sf = SWITCH_ON;
    if (sf != null) {
      const f = clamp(sf, 0, 17);
      const i0 = Math.floor(f + 1e-6);
      out.sw = [i0, Math.min(17, i0 + 1)];
      out.frac = f - i0;
      out.lit = 1 - f / 17;
      out.on = out.lit > 1e-4;
      out.off = out.lit < 1 - 1e-4;
    }
    return out;
  }

  /**
   * Prepare the frames a state (or list of states) will show. Call in build(); setState throws on
   * a frame that was not prepared. States without a switch position prepare both HQ sheets.
   */
  require(states) {
    for (const s of [].concat(states)) {
      const fr = this._framesOf(s);
      const both = !fr.sw.length;
      for (const k of KNOBS) {
        if (fr.knobs[k] == null) continue;
        if (fr.off || both || this.white) this.knobs[k].off.require([fr.knobs[k]]);
        if ((fr.on || both) && this.knobs[k].on) this.knobs[k].on.require([fr.knobs[k]]);
      }
      if (fr.mix != null) this.mix.require([fr.mix]);
      if (fr.sw.length) {
        this.sw[0].require([fr.sw[0]]);
        if (fr.frac > 1e-4) this.sw[1].require([fr.sw[1]]);
      }
    }
    return this;
  }

  /** Prepare every frame between two knob frames (a gesture), for one control. */
  requireFrames(control, f0, f1, { on = true, off = true } = {}) {
    const fs = range(f0, f1);
    if (control === "mix") this.mix.require(fs);
    else if (control === "switch") {
      this.sw[0].require(fs);
      this.sw[1].require(fs);
    } else {
      if (off || this.white) this.knobs[control].off.require(fs);
      if (on && this.knobs[control].on) this.knobs[control].on.require(fs);
    }
    return this;
  }

  /**
   * Prepare everything a cue render shows over [t0, t1] (sampled per video frame), e.g.
   * plate.requireRender(cues, "R04", 24, 28) for the Red shot with its HQ flip.
   */
  requireRender(cues, renderId, t0, t1, fps = 480) { // dense: time-warped cuts seek between 1/60 steps
    const n = Math.max(1, Math.round((t1 - t0) * fps));
    const states = [];
    for (let i = 0; i <= n; i++) states.push(cues.settingsAt(renderId, t0 + ((t1 - t0) * i) / n));
    return this.require(states);
  }

  /** The image URLs this plate draws (for preloading). */
  urls() {
    const u = [...new Set([this.plateOff.lo, this.plateOn.lo].map((n) => n.style.backgroundImage.slice(5, -2)))];
    if (this.hiRes) u.push(this.art.plate2x.plateOff, this.art.plate2x.plateOn);
    if (this.art.thumb && this.showThumb) u.push(this.art.thumb);
    for (const k of KNOBS) {
      u.push(...this.knobs[k].off.urls());
      if (this.knobs[k].on) u.push(...this.knobs[k].on.urls());
    }
    u.push(...this.mix.urls(), ...this.sw[0].urls(), ...this.sw[1].urls());
    return [...new Set(u)];
  }

  /**
   * Position on screen (relative to the parent): x/y is the window's top-left (top bar included),
   * or give cx/cy for its centre. dx/dy is an extra offset (G2 drift). Scale is a plain 2D
   * transform: the plate has no canvas inside, so it is seek-safe.
   */
  place({ x, y, cx, cy, scale, dx, dy } = {}) {
    const P = this.placement;
    if (scale != null) P.scale = scale;
    if (cx != null) P.x = cx - (this.width * P.scale) / 2;
    else if (x != null) P.x = x;
    if (cy != null) P.y = cy - (this.height * P.scale) / 2;
    else if (y != null) P.y = y;
    if (dx != null) P.dx = dx;
    if (dy != null) P.dy = dy;
    setStyle(this.el, "left", px(P.x));
    setStyle(this.el, "top", px(P.y));
    setStyle(this.el, "width", px(this.width * P.scale));
    setStyle(this.el, "height", px(this.height * P.scale));
    setStyle(this.el, "transform", P.dx || P.dy ? `translate(${px(P.dx)}, ${px(P.dy)})` : "");
    setStyle(this.inner, "transform", P.scale === 1 ? "" : `scale(${+P.scale.toFixed(6)})`);
    this._pickArt();
    return this;
  }

  // The product's plates up to scale 1, the 2x art above it. The unlit 2x plate reduces to the
  // shipped bitmap, so it switches at scale 1 invisibly; the lit 2x plate is sharper than the
  // editor's 638 px lit cache, so it fades in over scale 1.0 to 1.25 instead of popping.
  _pickArt() {
    if (!this.hiRes) return;
    const s = this.placement.scale * (this.outerScale || 1);
    const always = this.hiRes === "always";
    const offHi = always || s > 1.0001;
    const onA = always ? 1 : clamp((s - 1) / 0.25);
    const key = `${offHi}:${onA.toFixed(4)}`;
    if (key === this._hiKey) return;
    this._hiKey = key;
    setStyle(this.plateOff.lo, "visibility", offHi ? "hidden" : "");
    setStyle(this.plateOff.hi, "visibility", offHi ? "" : "hidden");
    setStyle(this.plateOn.lo, "visibility", onA >= 1 ? "hidden" : "");
    setStyle(this.plateOn.hi, "visibility", onA > 0 ? "" : "hidden");
    setStyle(this.plateOn.hi, "opacity", onA >= 1 ? "" : String(+onA.toFixed(4)));
  }

  /**
   * If the plate's parent is itself scaled (a camera group), tell the plate the extra factor so
   * that hiRes "auto" picks the art for the true on-screen scale.
   */
  setOuterScale(s) {
    this.outerScale = s;
    this._pickArt();
    return this;
  }

  /**
   * Close-up camera: place the plate at `zoom` (plate scale) with a control ("rate", "mix", "hq",
   * "color", "rateValue", ...) or a body point [x, y] (plate px) at the screen point `at` (parent
   * coordinates; default: where that point is now). Returns the placement. Knob frames are native
   * up to KNOB_NATIVE_SCALE (1.08) and magnified above it; the mix knob (512 px frames), readouts,
   * top bar and HQ lever stay sharp far beyond 2x; the backpanel switches to its 2x art above 1.
   */
  focus({ on, zoom, at = null, dx = 0, dy = 0 }) {
    let bxy;
    if (Array.isArray(on)) bxy = on;
    else if (typeof on === "string" && on.endsWith("Value")) {
      const [x, y, w, h] = this.G.values[on.slice(0, -5)];
      bxy = [bx(x + w / 2), by(y + h / 2)];
    } else {
      const r = this.controlRect(on);
      bxy = [r.cx, r.cy];
    }
    const target = at ?? this.toScreen(bxy[0], bxy[1]);
    const s = zoom ?? this.placement.scale;
    const x = target[0] - bxy[0] * s;
    const y = target[1] - (this.headerH + bxy[1]) * s;
    return this.place({ x, y, scale: s, dx, dy });
  }

  /** Body plate px -> screen px in the parent's coordinates, with the current placement. */
  toScreen(pxX, pxY) {
    const P = this.placement;
    return [P.x + P.dx + pxX * P.scale, P.y + P.dy + (this.headerH + pxY) * P.scale];
  }

  /** A control's centre and size in body plate px ({ cx, cy, size }). */
  controlRect(name) {
    const G = this.G;
    if (name === "color" || name === "thumb") {
      const i = Math.min(12, Math.floor(G.color[3] * 0.5));
      const w0 = G.color[2] - 2 * i;
      const t = this.thumbGeom || { x0: G.color[0] + i + w0 * 0.115, x1: G.color[0] + i + w0 * 0.885, w: G.color[3] * 0.5, h: G.color[3], y: G.color[1] };
      const cxE = this.cur.thumbCx ?? (t.x0 + t.x1) / 2;
      return { cx: bx(cxE), cy: by(t.y + t.h / 2), size: Math.max(t.w * KX, t.h * KY) };
    }
    if (name === "hq") {
      const [x, y, w, h] = G.hq;
      return { cx: bx(x + w / 2), cy: by(y + h * LEVER.cy), size: w * LEVER.size * KX };
    }
    const [x, y, w, h] = G[name];
    return { cx: bx(x + w / 2), cy: by(y + h / 2), size: w * KX };
  }

  /** A control's centre and size in screen px ({ cx, cy, size }), for rings and camera moves. */
  controlScreenRect(name) {
    const r = this.controlRect(name);
    const [cx, cy] = this.toScreen(r.cx, r.cy);
    return { cx, cy, size: r.size * this.placement.scale };
  }

  /**
   * Colour = sound (v5): a CSS filter saturate(sat) brightness(bright) on the plate body (backpanel,
   * knobs, mix, thumb, lever), never on the readouts, which keep the product's own colour. The
   * plate has no canvas, so the filter is seek-safe. topBar: also grade the top bar (default true).
   * keep: names of the readouts left ungraded (default: all six).
   */
  setGrade({ sat = 1, bright = 1, topBar = true, keep = null } = {}) {
    const f = sat === 1 && bright === 1 ? "" : `saturate(${+sat.toFixed(4)}) brightness(${+bright.toFixed(4)})`;
    for (const n of this._gradeNodes) setStyle(n, "filter", f);
    // keep: the readouts that stay in their own colour (default all of them), e.g. ["mix"].
    for (const [name, r] of Object.entries(this.readouts)) setStyle(r.node, "filter", !keep || keep.includes(name) ? "" : f);
    if (this.topbar && this.topbar.el) setStyle(this.topbar.el, "filter", topBar ? f : "");
    return this;
  }

  /**
   * state: { rate, depth, offset, width, color, mix } in display units (any subset),
   * hq (0/1) or switchFrame (0..17, float while the lever moves),
   * readouts: { rate: "0.60 Hz" | { text, from, progress }, ... } to override the text
   * (default: formatted from the values), frames: { rate: 47, mix: 78 } to force filmstrip frames.
   * Cues.plateStateAt(render, t) returns exactly this shape.
   */
  setState(state) {
    const c = this.cur;
    const fr = this._framesOf(state);
    if (fr.sw.length) {
      const key = `${fr.sw[0]}:${fr.frac.toFixed(4)}`;
      if (c.sw !== key) {
        c.sw = key;
        c.lit = fr.lit;
        this.sw[0].show(fr.sw[0]);
        const a = fr.frac > 1e-4 ? fr.frac : 0;
        this.sw[0].setOpacity(1 - a);
        this.sw[1].show(a > 0 ? fr.sw[1] : null);
        this.sw[1].setOpacity(a);
        // Lit plate follows the lever: 1 - frame / 17 (AnimatedToggleButton::getAnimationProgress).
        setStyle(this.plateOn.wrap, "opacity", String(+fr.lit.toFixed(4)));
        setStyle(this.plateOn.wrap, "visibility", fr.lit > 1e-4 ? "" : "hidden");
      }
    }
    const lit = c.lit ?? 0;
    for (const k of KNOBS) {
      const f = fr.knobs[k];
      const kn = this.knobs[k];
      // (1 - lit) off + lit on, premultiplied (see the constructor): lit 0 and 1 show one sheet.
      const onA = kn.on ? lit : 0;
      const offA = kn.on ? 1 - lit : 1;
      if (f != null) {
        if (offA > 0) kn.off.show(f);
        if (kn.on && onA > 0) kn.on.show(f);
      }
      kn.off.setOpacity(offA);
      if (kn.on) kn.on.setOpacity(onA);
    }
    if (fr.mix != null) this.mix.show(fr.mix);
    if (this.thumb && state.color != null) {
      const t = this.thumbGeom;
      const cxE = t.x0 + clamp(pFromValue("color", state.color)) * (t.x1 - t.x0);
      if (c.thumbCx !== cxE) {
        c.thumbCx = cxE;
        this.thumb.style.left = px(bx(Math.trunc(cxE - t.w / 2)));
      }
    }
    if (this.showReadouts) {
      for (const r of READOUTS) {
        const o = state.readouts && state.readouts[r];
        if (o != null) this.readouts[r].set(o);
        else if (state[r] != null) this.readouts[r].set(formatReadout(r, state[r]));
      }
    }
    if (state.trim != null && this.topbar && this.topbar.setTrim) this.topbar.setTrim(state.trim);
    return this;
  }
}

/** createPlate("green", opts) or createPlate(stateWithEngine, opts) (prepares and shows that state). */
export function createPlate(engineOrState, opts = {}) {
  if (typeof engineOrState === "string") return new Plate(engineOrState, opts);
  return new Plate(engineOrState.engine, { ...opts, state: engineOrState });
}

/** G2 plate drift in px: A sin(2 pi cycles), A = 4 px x min(1, Depth / 30%). */
export function driftPx(settings, amp = 4) {
  return amp * Math.min(1, settings.depth / 30) * Math.sin(TAU * settings.cycles);
}
